### PR TITLE
Created a new function for extracted a XLSX files

### PR DESCRIPTION
**Pull request by Kabilan-16**
Completed Excel Extraction

### CODE REVIEW

**Comment by Kabilan-16** [comment]
[sample.xlsx](https://github.com/user-attachments/files/18228036/sample.xlsx)
[sample.xlsx.txt](https://github.com/user-attachments/files/18228044/sample.xlsx.txt)
[charts.xlsx](https://github.com/user-attachments/files/18228048/charts.xlsx)
[charts.xlsx.txt](https://github.com/user-attachments/files/18228051/charts.xlsx.txt)
[Alldatas.xlsx](https://github.com/user-attachments/files/18228053/Alldatas.xlsx)
[Alldatas.xlsx.txt](https://github.com/user-attachments/files/18228055/Alldatas.xlsx.txt)
[images.xlsx](https://github.com/user-attachments/files/18228057/images.xlsx)
[images.xlsx.txt](https://github.com/user-attachments/files/18228061/images.xlsx.txt)

**Review by SaravanakumarR2018 — COMMENTED** [review]
This Stacked column chart does not have certain dates like 3-11 from the table

Pasted Graphic
Pasted Graphic 1


Try checking whether we are able to get this text from the picture
Google
Pasted Graphic 5

**Comment by Kabilan-16** [comment]
[sample.xlsx](https://github.com/user-attachments/files/18239163/sample.xlsx)
[sample.xlsx.txt](https://github.com/user-attachments/files/18239164/sample.xlsx.txt)
[images.xlsx](https://github.com/user-attachments/files/18239165/images.xlsx)
[images.xlsx.txt](https://github.com/user-attachments/files/18239167/images.xlsx.txt)
[Alldatas.xlsx](https://github.com/user-attachments/files/18239169/Alldatas.xlsx)
[Alldatas.xlsx.txt](https://github.com/user-attachments/files/18239172/Alldatas.xlsx.txt)
[charts.xlsx](https://github.com/user-attachments/files/18239175/charts.xlsx)
[charts.xlsx.txt](https://github.com/user-attachments/files/18239177/charts.xlsx.txt)

**Comment by Kabilan-16** [comment]
[Alldatas.xlsx](https://github.com/user-attachments/files/18239477/Alldatas.xlsx)
[Alldatas.xlsx.txt](https://github.com/user-attachments/files/18239480/Alldatas.xlsx.txt)
[sample.xlsx](https://github.com/user-attachments/files/18239482/sample.xlsx)
[sample.xlsx.txt](https://github.com/user-attachments/files/18239484/sample.xlsx.txt)
[charts.xlsx](https://github.com/user-attachments/files/18239486/charts.xlsx)
[charts.xlsx.txt](https://github.com/user-attachments/files/18239487/charts.xlsx.txt)
[images.xlsx](https://github.com/user-attachments/files/18239494/images.xlsx)
[images.xlsx.txt](https://github.com/user-attachments/files/18239497/images.xlsx.txt)

**Review by SaravanakumarR2018 — APPROVED** [review]

**Pull request merged**
